### ISSUE TITLE
devTools・開発ツール周りの表記整理

### ISSUE THREAD

**Issue by 2YY** [angular/angular-ja#780]
下記の翻訳作業から派生。
https://github.com/angular/angular-ja/pull/778#discussion_r970289259

`devTools` `開発者ツール` `開発ツール` といった、似た語彙の表記がサイト内でいくつか有り、
統一した方が閲覧者にとって良い箇所が有るか確認・修正する必要が有るか。

**Comment by IRod22** [comment]
*(Google 翻訳で翻訳)*

昨日はちゃんと紹介できなくてごめんなさい。 私の名前は Ivan Rodriguez です。私は Angular の組織のプロフィールとリポジトリを調べていて、何らかの形で助けや知識を提供できないかと考えていたので、そのコメントを投稿しました。 私のコメントと調査がこの問題の解決に役立つことを願っています。このリポジトリは日本の Angular コミュニティ向けであることを知っているので、招待なしでここに来て申し訳ありません。

---

*(Original)*

I am sorry I did not give a proper introduction yesterday. My name is Ivan Rodriguez, and I was checking out Angular's organization profile and repositories, and I was seeing if I could offer some help or knowledge in some way, which is why I posted that comment. I hope my comment and research helped resolve this issue, I know this repository is for the Japanese Angular community, so I apologize for being here without an invite.

**Comment by IRod22** [comment]
@lacolaco、@2YY、MDN によると、開発者ツール、開発者ツール、および devTools はまったく同じことを意味するため、この問題はクローズできます (上記のリンクと引用を参照)。

**Comment by 2YY** [comment]
@IRod22
レスポンスが遅くすみません！
下記でコメント戴いている通り、現状のままでも、ドキュメントを閲覧する上で直接的に困ることが無さそうであるため、クローズしたいと思います。
https://github.com/angular/angular-ja/issues/780#issuecomment-1333885497
(問題あれば再オープン頂けますと幸いです › @lacolaco )

ありがとうございました！

**Comment by IRod22** [comment]
@2YY、どういたしまして！また、私たちが対話を始めたばかりであることは知っていますが、私の小さなプロジェクトをチェックアウトするよう招待してもよろしいですか? 私は [NimbleUI](https://github.com/IRod22/NimbleUI) というフロントエンド ライブラリに取り組んでおり、そこでコミュニティを成長させたいと考えています。 興味のある方は、README や行動規範などの「.md」ファイルが英語であることをお知らせしたいと思います。そのため、Google 翻訳のブラウザ拡張機能をインストールすることをお勧めします。 そうでない場合は、大丈夫です。
